version: "3.3"
services:
  spark-master:
    image: bitnami/spark:latest
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./apache-spark/python:/opt/spark-apps
      - ./apache-spark/data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: bitnami/spark:latest
    ports:
      - "9091:8080"
      - "7002:7002"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - ./apache-spark/python:/opt/spark-apps
      - ./apache-spark/data:/opt/spark-data
  spark-worker-b:
    image: bitnami/spark:latest
    ports:
      - "9092:8080"
      - "7001:7001"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
      - ./apache-spark/python:/opt/spark-apps
      - ./apache-spark/data:/opt/spark-data